# Generated by Django 4.1 on 2022-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='expected',
            field=models.IntegerField(blank=True),
        ),
    ]
