# Generated by Django 4.1 on 2022-11-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_report_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='item_pics'),
        ),
    ]
