# Generated by Django 4.1 on 2022-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='actual',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='expected',
            field=models.IntegerField(),
        ),
    ]
