# Generated by Django 4.1 on 2022-11-27 05:59

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='code'),
        ),
    ]
