# Generated by Django 4.1 on 2023-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_report_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
