# Generated by Django 4.1 on 2023-06-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0011_alter_area_unique_together'),
        ('inventory', '0019_alter_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('viewed', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authencation.area')),
                ('reports', models.ManyToManyField(blank=True, to='inventory.report')),
            ],
        ),
    ]
