# Generated by Django 4.1 on 2023-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_reporttable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reporttable',
            constraint=models.UniqueConstraint(fields=('area', 'date'), name='unique_area_date_combination'),
        ),
    ]
