# Generated by Django 4.1 on 2023-07-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_reporttable_unique_area_date_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
