# Generated by Django 4.1 on 2022-09-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0002_user_active_user_admin_user_email_user_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
