# Generated by Django 4.1 on 2022-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_incharge',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
