# Generated by Django 4.1 on 2023-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0004_user_area_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='area_incharge',
        ),
        migrations.AddField(
            model_name='user',
            name='area_incharge',
            field=models.ManyToManyField(to='authencation.area'),
        ),
    ]
