# Generated by Django 4.1 on 2023-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0005_area_remove_user_area_incharge_user_area_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_incharge',
        ),
        migrations.AddField(
            model_name='user',
            name='area_incharge',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
