# Generated by Django 4.1 on 2023-04-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authencation', '0009_remove_user_area_incharge_user_area_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_incharge',
            field=models.ManyToManyField(blank=True, to='authencation.area'),
        ),
    ]
